### ISSUE TITLE
OpenPGP

### ISSUE THREAD

**Issue by 0xF7A4C6** [opulentfox-29/protonmail-api-client#1]
You may look here, page contains another pgp packages,
https://pypi.org/project/py-pgp

**Comment by opulentfox-29** [comment]
Unfortunately, all packages from this list, except PGPy, are outdated or a wrapper for gpg.

**Comment by stefanodvx** [comment]
why, instead, don't you use python-gnupg instews of playwright?

**Comment by 0xF7A4C6** [comment]
slow

**Comment by opulentfox-29** [comment]
1. python-gnupg is a wrapper over GPG, which means that the user must take care to install it himself, which can cause great difficulties, especially for Windows users
2. GPG does not have the `DecryptSessionKeys` and `EncryptSessionKeys` functions, as I understand these functions are developed only in `OpenPGP.js`
