### ISSUE TITLE
Incorrect mail formatting

### ISSUE THREAD

**Issue by stefanodvx** [opulentfox-29/protonmail-api-client#15]
When sending mail with plain text, every newline character (\n) is ignored.

How to reproduce: Just use the library to send an email that contains new line characters.

Example:
"Word1
Word2"
will be sent as...
"Word1Word2"

**Comment by opulentfox-29** [comment]
now you can send text not as html using the `is_html=False` parameter and the newline character `\n` will work:
```python
new_message = proton.create_message(
    recipients=['to1@gmail.com'],
    subject='hello',
    body='hello1\nhello2'
)
message = proton.send_message(new_message, is_html=False)
```
but in html mode you will have to use `<br/>`
```python
new_message = proton.create_message(
    recipients=['to1@gmail.com'],
    subject='hello',
    body='hello1<br/>hello2'
)
message = proton.send_message(new_message, is_html=True)
```
