### ISSUE TITLE
wait_for_new_message() returns when an unread message is read

### ISSUE THREAD

**Issue by CVasilakis** [opulentfox-29/protonmail-api-client#22]
My goal is to receive a notification when a new email arrives. The script is intended to work as a service (always running):
```python
from protonmail import ProtonMail
import apprise
import pyotp
import time

# Apprise configuration
appNotif = apprise.Apprise()
appNotif.add('secret_app_ID')

# ProtonMail credentials
username = "username"
password = "password"
totp = pyotp.TOTP('secret')

proton = ProtonMail()
proton.login(username, password, totp.now)

# Wait for new messages
while(True):
    new_message = proton.wait_for_new_message(interval=60, timeout=0, rise_timeout=False, read_message=False)
    appNotif.notify(title='ProtonMail - New email received...',
                    body=f'From: {new_message.sender.address}\nSubject: {new_message.subject}.')
```
This script works just fine when a new email is received, but i also receive a notification when i open the web client on my browser and read an unread email. The same happens if i have an old unread email and i decide to read it (then i receive a notification with the info of the old email that i just read).

Based on the name of the function "wait_for_new_message" i suspect that this is not an intended behavior. Of course if there is another way to achive my goal i'm open to suggestions.

**Comment by opulentfox-29** [comment]
You are right, the function `wait_for new_message` could consider any event (for example, reading a message) as receiving a new message. Fixed in the new version [1.6.1](https://pypi.org/project/protonmail-api-client/1.6.1/)
