### ISSUE TITLE
Add "isDraft" to message or Labels in general

### ISSUE THREAD

**Issue by spookyahell** [opulentfox-29/protonmail-api-client#24]
Correct me if I'm wrong, but I don't see a way to interact with labels yet.

I can see Label-ids for a message but I don't see where I'd retrieve a list of such labels.

**Comment by opulentfox-29** [comment]
In new [1.7.0](https://pypi.org/project/protonmail-api-client/1.7.0/) version:
- added working with labels
- added method `is_draft` to message

# working wtih labels
Now you can get labels by type id:
```python
labels = proton.get_labels_by_type_id(label_id)
```
Possible types:
- 1 - User's custom labels.
- 2 - Actually, I have no idea what it is. If this returned a non-empty list for you, please let me know what it is.
- 3 - User's custom folders.
-  4 - ProtonMail's system labels/folders (inbox, drafts, sent, spam, etc.)

Or you can get labels in another way:
```python
user_folders = proton.get_user_folders()
user_labels = proton.get_user_labels()
system_labels = proton.get_system_labels()
```
Or you can get all labels:
```python
labels = proton.get_all_labels()
```
Convert label_ids to label_obj in message:
```python
print(message.labels)  # ['1', '5', '8', '15']
message.convert_labels(labels)
print(message.labels)  # [Label(id='8', name='Drafts', ...), ...]
```

Set/Unset label for messages:
```python
proton.set_label_for_messages(label_or_id=label, messages_or_ids=[message])
proton.unset_label_for_messages(label_or_id=label, messages_or_ids=[message])
```

Get messages by label:
```python
messages = proton.get_messages(label_or_id='4')  # spam
```

# Message is_draft method
```python
message.is_draft()
```
