### ISSUE TITLE
import Error can't not use

### ISSUE THREAD

**Issue by z2labplus** [opulentfox-29/protonmail-api-client#26]
root@facechecker:~# ipython
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.27.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from protonmail import ProtonMail
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from protonmail import ProtonMail

File /usr/local/lib/python3.10/dist-packages/protonmail/__init__.py:1
----> 1 from .client import ProtonMail

File /usr/local/lib/python3.10/dist-packages/protonmail/client.py:15
     13 from math import ceil
     14 from threading import Thread
---> 15 from typing import Optional, Coroutine, Union, Self
     17 import unicodedata
     18 from requests import Session

ImportError: cannot import name 'Self' from 'typing' (/usr/lib/python3.10/typing.py)

(base) root@mail:~# ipython
Python 3.9.16 (main, Mar  8 2023, 14:00:05) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from protonmail import ProtonMail
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 1
----> 1 from protonmail import ProtonMail

File ~/miniconda3/lib/python3.9/site-packages/protonmail/__init__.py:1
----> 1 from .client import ProtonMail

File ~/miniconda3/lib/python3.9/site-packages/protonmail/client.py:38
     34 from .pgp import PGP
     35 from .utils.utils import bcrypt_b64_encode
---> 38 class ProtonMail:
     39     """
     40     Client for api protonmail.
     41     """
     42     def __init__(self, proxy: Optional[str] = None, logging_level: Optional[int] = 2, logging_func: Optional[callable] = print):

File ~/miniconda3/lib/python3.9/site-packages/protonmail/client.py:1261, in ProtonMail()
   1257 def _delete(self, base: str, endpoint: str, **kwargs) -> Response:
   1258     return self.__request('delete', base, endpoint, **kwargs)
   1260 @__delete_duplicates_cookies_and_reset_domain
-> 1261 def __request(self, method: str, base: str, endpoint: str, **kwargs) -> Response:
   1262     methods = {
   1263         'get': self.session.get,
   1264         'post': self.session.post,
   1265         'put': self.session.put,
   1266         'delete': self.session.delete
   1267     }
   1268     response = methods[method](f'{urls_api[base]}/{endpoint}', **kwargs)

TypeError: 'staticmethod' object is not callable

**Comment by opulentfox-29** [comment]
> ImportError: cannot import name 'Self' from 'typing' (/usr/lib/python3.10/typing.py)

This bug was [fixed](https://github.com/opulentfox-29/protonmail-api-client/pull/13/commits/c9c8dbc3c104873ac2c35d6da233be7e08f622dd) in version 1.3.5, try to install the current version (1.7.0)
You might have problems with `pip`, check this issue:: https://github.com/opulentfox-29/protonmail-api-client/issues/21

**Comment by opulentfox-29** [comment]
On Linux with `pip<23` this project could not be installed and the project version was automatically downgraded to `1.3.4`, which had wheel in the build, this happened, for example, on default Ubuntu 22.04

In the new version `1.7.2` I included wheel, so now everyone can install new versions
