### ISSUE TITLE
Getting error `'staticmethod' object is not callable`

### ISSUE THREAD

**Issue by Doocter** [opulentfox-29/protonmail-api-client#27]
Getting this error:
Traceback (most recent call last):
  File "/root/OTPViewer/demo.py", line 1, in <module>
    from protonmail import ProtonMail
  File "/root/OTPViewer/venv/lib/python3.9/site-packages/protonmail/__init__.py", line 1, in <module>
    from .client import ProtonMail
  File "/root/OTPViewer/venv/lib/python3.9/site-packages/protonmail/client.py", line 38, in <module>
    class ProtonMail:
  File "/root/OTPViewer/venv/lib/python3.9/site-packages/protonmail/client.py", line 1261, in ProtonMail
    def __request(self, method: str, base: str, endpoint: str, **kwargs) -> Response:
TypeError: 'staticmethod' object is not callable

On this demo code:
from protonmail import ProtonMail

def main():
    proton = ProtonMail()

    username = "your_username@proton.me"
    password = "your_password"

    try:
        proton.login(username, password)
        print("Successfully logged in to ProtonMail")

        messages = proton.get_messages()
        print(f"Total messages: {len(messages)}")

        if messages:
            latest_message = proton.read_message(messages[0])
            print("\nLatest message details:")
            print(f"Sender: {latest_message.sender.address}")
            print(f"Subject: {latest_message.subject}")
            print(f"Body preview: {latest_message.body[:100]}...")

        proton.logout()
        print("\nSuccessfully logged out from ProtonMail")

    except Exception as e:
        print(f"An error occurred: {str(e)}")

if __name__ == "__main__":
    main()

**Comment by opulentfox-29** [comment]
There is a bug in python 3.9 where wrapper can't be a static method of a class, so in the new version I moved it to another file.
So you can update`protonmail-api-client` version to [1.7.1](https://pypi.org/project/protonmail-api-client/1.7.1/) or update your Python version to 3.10
