### ISSUE TITLE
Can't read message: NoKeysForDecryptThisMessage("No keys for decrypt this message...")

### ISSUE THREAD

**Issue by HopiumCurrency** [opulentfox-29/protonmail-api-client#31]
might be missing something but this is error i get from proton.read_message(messages[0])

AppData\Roaming\Python\Python39\site-packages\protonmail\pgp.py", line 33, in decrypt
    raise NoKeysForDecryptThisMessage(NoKeysForDecryptThisMessage.__doc__, 'you need private key for public key:', fingerprint)
protonmail.exceptions.NoKeysForDecryptThisMessage: ("\n    No keys for decrypt this message,\n    maybe you created new key then re-login,\n    if you deleted key then you can't decrypt this message\n    "

Do I have to tweak something on my protonmail account first ?

Thanks.

**Comment by opulentfox-29** [comment]
The `NoKeysForDecryptThisMessage` error occurs if you have changed something in the "[Email encryption keys](https://account.proton.me/u/0/mail/encryption-keys#addresses)" section of the ProtonMail settings.

![image](https://github.com/user-attachments/assets/12d9ac5f-38f3-4d63-82e2-0232cb9e697b)

If you created a new key or changed the primary key, you just need to re-login:
```python
proton = ProtonMail()
proton.login(username, password)

proton.save_session('session.pickle')
```
And then you will be able to read your message:
```python
messages = proton.get_messages()
message = proton.read_message(messages[0])
```

But if you deleted the key then you can no longer read your message, even in the web interface if you open this message you will get an error:

![image](https://github.com/user-attachments/assets/beb94b50-7310-497b-8cc1-f3e976583316)

If you exported the private key before deleting it, you can import it and re-login:

![image](https://github.com/user-attachments/assets/eda8ce0b-8ebe-4883-b15d-ca8603643898)

```python
proton = ProtonMail()
proton.login(username, password)

proton.save_session('session.pickle')
```
By the way, if you saved the protonmail-api-client session before deleting the key, you can restore it:
```python
proton = ProtonMail()
proton.load_session('session.pickle', auto_save=True)

for pair in proton.pgp.pairs_keys:
    if pair.is_user_key:
        continue
    with open(f'privatekey-{pair.fingerprint_private}.asc', 'wb') as f:
        f.write(pair.private_key.encode())
    print(f"For key: {pair.fingerprint_private} password is {pair.passphrase}")
```
And then just import the key on the site.

If you reset your password, you also lose access to your messages, but there are ways to restore it.
read more: https://proton.me/support/recover-encrypted-messages-files

Try to open this letter in the ProtonMail web interface if it does not open, then it will not open in the API client, but if it opens, then try to re-login, if this does not help, write to me about it.
