### ISSUE TITLE
can't decrypt messages by other addresses in 1 account (premium only)

### ISSUE THREAD

**Issue by ajkessel** [opulentfox-29/protonmail-api-client#33]
Using part of your example code:
```
from protonmail import ProtonMail
from pprint import pprint
username = [redacted]
password = [redacted]
proton = ProtonMail()
proton.login(username, password)
messages = proton.get_messages()
message = proton.read_message(messages[0])
pprint.pp(message)
```
I get the following
```
login success
enter 2FA code: [redacted]
got cookies
got user keys
got email keys
...
Traceback (most recent call last):
  File "/home/adam/src/proton/test.py", line 14, in <module>
    message = proton.read_message(messages[0])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/protonmail/client.py", line 128, in read_message
    message.body = self.pgp.decrypt(message.body)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/protonmail/pgp.py", line 33, in decrypt
    raise NoKeysForDecryptThisMessage(NoKeysForDecryptThisMessage.__doc__, 'you need private key for public key:', fingerprint)
protonmail.exceptions.NoKeysForDecryptThisMessage: ("\n    No keys for decrypt this message,\n    maybe you created new key then re-login,\n    if you deleted key then you can't decrypt this message\n    ", 'you need private key for public key:', '[redacted]')
```
Am I missing something?

I see issue #31 now but I've never changed my email encryption keys -- this is a new account.

**Comment by opulentfox-29** [comment]
I just created a new account, and even enabled 2FA like you, and everything works for me, it looks like something is wrong with your settings (having 2FA confirms that you changed the settings)

Try to check the following information:
1. can you open this email in a browser?
2. does reading other emails work?
3. did you receive the email or send it?
4. who is your interlocutor (protonmail/gmail, etc.)

Also try to create a new account and not change any settings at all, and try reading emails, if it works, then try to set the same settings on the new account as on the problematic one, trying to figure out which setting is giving an error

**Comment by ajkessel** [comment]
>     1. can you open this email in a browser?
>     2. does reading other emails work?
>     3. did you receive the email or send it?
>     4. who is your interlocutor (protonmail/gmail, etc.)

I can read all my emails in the browser or via a MUA+Hydroxide (the OSS go-IMAP bridge). I haven't found an email yet that doesn't render properly in the browser, but every email I retrieve via portonmail-api-client fails with this same error, whether it is sent or received.

I just sent myself a message completely within the web UI, so the most recent message was just a message from myself on Protonmail. Same issue--the header shows up correctly, but `read_message` is unable to decode the contents.

> Also try to create a new account and not change any settings at all, and try reading emails, if it works, then try to set the same settings on the new account as on the problematic one, trying to figure out which setting is giving an error.

I can try this next... is there anything that is persisting between runs of protonmail-api-client, other than what you optionally save in a session pickle, that could be the issue here?

**Comment by opulentfox-29** [comment]
> is there anything that is persisting between runs of protonmail-api-client, other than what you optionally save in a session pickle, that could be the issue here?

no, there is no cache between client runs.

> I don't need to manually export keys from the web UI to use them with protonmail-api-client, right? It should just happen automatically as part of the login process?

yes, when running the `login` method the client automatically downloads and decrypts all keys

**Comment by ajkessel** [comment]
Could the issue be that I have four email addresses associated with my account, each with its own encryption key? They're all the same account and password on Proton, but maybe this client isn't using the right key? Do I need to somehow login with each of the four email addresses as usernames?

**Comment by ajkessel** [comment]
Bingo, that's the issue. My emails are encrypted against different keys, apparently, depending on which of my four addresses receives them. If I match the login username to the recipient address, it uses the right key and then can decrypt.

Is there a suggested way to accommodate this situation with this library? I didn't intentionally create four different keys; this is just what happened apparently by configuring four aliases for my Proton account.

**Comment by opulentfox-29** [comment]
I don't quite understand how you associated 4 email addresses to 1 account?

There are 2 types of encryption keys:
1. `Email encryption keys` - can be any number, the client will be able to work with all
2. `Account keys` - I've never checked what will happen if there are more than 1

![image](https://github.com/user-attachments/assets/bcf70ff3-0ae4-42c8-90f6-7abad3175467)

If you just clicked the `Switch or add account` button it doesn't affect anything (it just saves cookies in your browser from different accounts)
![image](https://github.com/user-attachments/assets/55539fe6-a65f-4987-857f-53d8877a8002)

**Comment by opulentfox-29** [comment]
> configuring four aliases for my Proton account

how did you do this? how can i reproduce the error?

**Comment by ajkessel** [comment]
![image](https://github.com/user-attachments/assets/18a94fc2-2e15-49d7-aa20-7212de03fd6e)

**Comment by ajkessel** [comment]
I didn't do anything to intentionally cause different PGP keys for each alias, but apparently that is default behavior.

Presumably, the client has access to all of the keys, since one login through the web interface (or, e.g. via Proton Bridge or Hydroxide) gives you access to all email encrypted against all of those different keys.

**Comment by opulentfox-29** [comment]
This is a paid feature, so I won't be able to reproduce it unless you provide me with such an account.
![image](https://github.com/user-attachments/assets/af5836b7-99b1-4a72-b343-51ccecf60cf8)

**Comment by ajkessel** [comment]
I think I get two accounts with my paid subscription so I would be open to creating one for you for testing purposes although I might take it back some day, if you're ok with that. What's the best way to communicate outside of this channel? I'm on Matrix, Discord, WhatsApp, IRC, Signal, etc. or just email! Any channel works.

**Comment by opulentfox-29** [comment]
let's send it to this email: jasBUHd28_21cv@proton.me

(the new one has already been restricted :) )

**Comment by ajkessel** [comment]
I sent you a family invite, let me know if that didn't work.

**Comment by opulentfox-29** [comment]
![image](https://github.com/user-attachments/assets/56988f4b-34ca-4811-b3dd-d416063bfb48)

I got premium but there is no "add address" button

**Comment by ajkessel** [comment]
Maybe only the admin can add aliases? I added one for you, let me know if you don't see it.

**Comment by opulentfox-29** [comment]
I was able to reproduce and fix the problem, now you can install the [new version](https://pypi.org/project/protonmail-api-client/2.0.0/) and read messages sent to different addresses.

Also, now you can send messages from different addresses:
```python
new_message = proton.create_message(
    recipients=["to1@proton.me", "to2@gmail.com"],
    subject="My first message",
    body="Hello world",
)

sent_message = proton.send_message(
    new_message,
    account_address=proton.account_addresses[1]
)
```
![image](https://github.com/user-attachments/assets/6eae6348-0498-4a9b-8870-db18e2ec888b)

Thanks for providing premium to experiment with this feature.

**Comment by ajkessel** [comment]
Wow, that's great! Impressed with how quickly you figured it out.
