### ISSUE TITLE
ValueError: Invalid padding bytes.

### ISSUE THREAD

**Issue by ajkessel** [opulentfox-29/protonmail-api-client#35]
Latest build fixed my last issue, thanks again!

It mostly works now, but I get this occasionally:
```
Traceback (most recent call last):
  File "/home/adam/src/proton/z.py", line 12, in <module>
    result = proton.read_message(message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/protonmail/client.py", line 126, in read_message
    message.body = self.pgp.decrypt(message.body)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/protonmail/pgp.py", line 39, in decrypt
    message = key.decrypt(encrypted_message).message
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/pgpy/decorators.py", line 131, in _action
    return action(_key, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/pgpy/pgp.py", line 2585, in decrypt
    return self.subkeys[skid].decrypt(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/pgpy/decorators.py", line 131, in _action
    return action(_key, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/pgpy/pgp.py", line 2590, in decrypt
    alg, key = pkesk.decrypt_sk(self._key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/pgpy/packet/packets.py", line 225, in decrypt_sk
    m = bytearray(self.ct.decrypt(decrypter, *decargs))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/pgpy/packet/fields.py", line 1773, in decrypt
    return padder.update(_m) + padder.finalize()
                               ^^^^^^^^^^^^^^^^^
ValueError: Invalid padding bytes.
```
It looks like this error is triggered when executing `read_message` on a sent message (i.e. from me) that was sent via the bridge from my MUA (Thunderbird). The received messages and messages sent from me on the website are not generating this error.

**Comment by opulentfox-29** [comment]
I sent messages via Thunderbird using Proton Mail Bridge, from different addresses and to different mails (protonmail, gmail) and in protonmail-api-client I was able to read them.
![image](https://github.com/user-attachments/assets/34573a2c-0681-423c-8977-9570cd1c4595)
```python
messages = proton.get_messages()
m = proton.read_message(messages[0])
print(f"message subject: {m.subject}")
m = proton.read_message(messages[1])
print(f"message subject: {m.subject}")
```
```
login success
got cookies
got user keys
got email keys
_async_get_messages: 100%|██████████| 2/2 [00:00<00:00,  2.73it/s]
message subject: tfghtfghfg
message subject: hello from thunderbird
```

Maybe you have some unusual settings?
here are my Proton Mail Bridge settings
![image](https://github.com/user-attachments/assets/59b22666-f25e-4bff-8c7a-71fab661c753)

**Comment by ajkessel** [comment]
Nothing unusual although I don't recall now if this mail was sent via Thunderbird-->Official Bridge or Thunderbird-->Hydroxide.

Is there more logging/debugging I can enable to see why this particular error occurs with this particular sent email?

**Comment by opulentfox-29** [comment]
There is very little logging here, and it would not help in this case, the error says that the encryption key is probably in some incorrect format.

Try sending similar messages using Bridge/Hydroxide to try to reproduce the error.

You can also look at the keys to check that their format is the same as those that work:
```python
for i in proton.pgp.pairs_keys:
    print(i.to_dict())
```
Еhe keys should be similar (except for the account key `'is_user_key': True`) and have the same length, although I noticed that the key not from the main address has a longer length, but still works.

**Comment by ajkessel** [comment]
The lengths are slightly different -- is this a problem?
```
for i in proton.pgp.pairs_keys:
    d=i.to_dict()
    if not d['public_key']:
        d['public_key']=''
    print(f'primary: {d['is_primary']} user: {d['is_user_key']} priv: {len(d['private_key'])} pub: {len(d['public_key'])}')
```
Gives:
```
primary: True user: True priv: 919 pub: 0
primary: True user: False priv: 899 pub: 901
primary: True user: False priv: 890 pub: 897
primary: True user: False priv: 882 pub: 884
primary: True user: False priv: 890 pub: 892
```
Also, here's a message that generates the padding exception:
```
Message(id='1DO7aiGE__wa6lUMFs_-UfVsJw2odmRc4p6BXaxAl6QeL2JW3oLo2bdXEipWFGEMqfR7RB4_HApoh6QnDlag3g==',
        conversation_id='9_xIP-gO_kWUeRLt8R0QU2XZzFm-GjfTmznXysHnk52MHKvf3Cuy0VMiNpbBQCUWcWae-7bN26vL0KKw-MBbeA==',
        subject='[redacted]',
        unread=0,
        sender=UserMail(name='[redacted]',
                        address='[redacted]',
                        extra={'Address': '[redacted]',
                               'BimiSelector': None,
                               'DisplaySenderImage': 0,
                               'IsProton': 0,
                               'IsSimpleLogin': 0,
                               'Name': '[redacted]'}),
        recipients=[UserMail(name='[redacted]',
                             address='[redacted]',
                             extra={'Address': '[redacted]',
                                    'Group': '',
                                    'IsProton': 0,
                                    'Name': '[redacted]'})],
        time=1733590479,
        size=925,
        body='',
        type='',
        labels=['2', '5', '7', '15'],
        attachments=[],
        extra={'AddressID': 'gaiSVrJ1ctGZMTlvRUiuDytX5Dm_WXD_CplyaToiKfJ1x5xnnxZsMRtCTA5q6_a4EKQwfiQemUECpvzln_HLrg==',
               'AttachmentInfo': {},
               'AttachmentsMetadata': [],
               'BCCList': [],
               'BimiSelector': None,
               'CCList': [{'Address': '[redacted]',
                           'Group': '',
                           'IsProton': 0,
                           'Name': '[redacted]'}],
               'ConversationID': '9_xIP-gO_kWUeRLt8R0QU2XZzFm-GjfTmznXysHnk52MHKvf3Cuy0VMiNpbBQCUWcWae-7bN26vL0KKw-MBbeA==',
               'DisplaySenderImage': 0,
               'DisplaySnoozedReminder': False,
               'ExpirationTime': 0,
               'ExternalID': '[redacted]',
               'Flags': 8198,
               'ID': '1DO7aiGE__wa6lUMFs_-UfVsJw2odmRc4p6BXaxAl6QeL2JW3oLo2bdXEipWFGEMqfR7RB4_HApoh6QnDlag3g==',
               'IsEncrypted': 5,
               'IsForwarded': 0,
               'IsProton': 0,
               'IsReplied': 0,
               'IsRepliedAll': 0,
               'LabelIDs': ['2', '5', '7', '15'],
               'NumAttachments': 0,
               'Order': 5100343495520,
               'Sender': {'Address': '[redacted]',
                          'BimiSelector': None,
                          'DisplaySenderImage': 0,
                          'IsProton': 0,
                          'IsSimpleLogin': 0,
                          'Name': '[redacted]'},
               'SenderAddress': '[redacted]',
               'SenderName': '[redacted]',
               'Size': 925,
               'SnoozeTime': 0,
               'SpamScore': 0,
               'Subject': '[redacted]',
               'Time': 1733590479,
               'ToList': [{'Address': '[redacted]',
                           'Group': '',
                           'IsProton': 0,
                           'Name': '[redacted]'}],
               'Type': 2,
               'Unread': 0})
```

**Comment by ajkessel** [comment]
FWIW, I dumped the encrypted message for one of the emails that is triggering the exception and was able to decrypt it with gpg at the command line using my Proton keys. And the one that is breaking protonmail-api-client is not encrypted with a different key than ones that are working fine.

**Comment by opulentfox-29** [comment]
> The lengths are slightly different -- is this a problem?

I don't know, my length is the same everywhere, except for the new address that you gave me, but your other messages work

```
primary: True user: True priv: 919 pub: 0
primary: True user: False priv: 907 pub: 913
primary: False user: False priv: 907 pub: 913
primary: False user: False priv: 907 pub: 913
primary: True user: False priv: 1102 pub: 1104
```

> Also, here's a message that generates the padding exception:

the message you sent looks completely normal, you need to look at its encrypted part and the encryption key:
```python
message_id = messages[0].id
response = proton._get('mail', f'mail/v4/messages/{message_id}')
encrypted_message = proton._convert_dict_to_message(response.json()['Message'])

encrypted_body = encrypted_message.body
pgp_message = proton.pgp.message(encrypted_body)  # problem pgp message
fingerprint = proton.pgp._get_public_fingerprint_from_message(pgp_message)

pair = proton.pgp._get_pair_keys(fingerprint=fingerprint)  # problem key
private_key = pair.private_key
passphrase = pair.passphrase

pgp_private_key, _ = proton.pgp.key(private_key)
with pgp_private_key.unlock(passphrase) as key:
    message = key.decrypt(pgp_message).message  # there will be error
    
```
But that won't do much, unless you can check that `passphrase` is a valid hex*, and `private_key` starts with `-----BEGIN PGP PRIVATE KEY BLOCK-----\nVersion: ProtonMail`

*hex is a 16 byte encoding, it contains only numbers from 0 to 9 and letters from `A` to `F`

**Comment by opulentfox-29** [comment]
> the one that is breaking protonmail-api-client

The problem is clearly in `PGPy` but it has already been abandoned, the last update was Nov 24, 2022. but there are no other pgp/gpg libraries in python.

> was able to decrypt it with gpg

You can try to reproduce this on `PGPy` and see if the error persists:
```python
from pgpy import PGPMessage, PGPKey

pgp_private_key, _ = PGPKey.from_blob('your private key')
pgp_message = PGPMessage.from_blob('you encrypted message')

with pgp_private_key.unlock('your passphrase') as key:
    message = key.decrypt(pgp_message).message
```

Although if you exported the key from proton, then perhaps it will work here, because when you export the key, proton decrypts it and re-encrypts it using the password that you enter, perhaps during this process it gives you a valid key, but continues to store the "incorrect" one (and OpenPGP.js in the web interface can work with "incorrect" keys)

But you better focus on trying to reproduce the creation of such a broken message, because without the encrypted message, the key and the password, I can't try to figure out how to fix it.

I already tried sending the message via bridge but it worked for me, and I haven't been able to get hydroxide to work yet, you try.

**Comment by ajkessel** [comment]
pgpy also fails
```
Traceback (most recent call last):
  File "/home/adam/src/proton/a.py", line 41, in <module>
    message = key.decrypt(pgp_message).message
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/pgpy/decorators.py", line 131, in _action
    return action(_key, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/pgpy/pgp.py", line 2585, in decrypt
    return self.subkeys[skid].decrypt(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/pgpy/decorators.py", line 131, in _action
    return action(_key, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/pgpy/pgp.py", line 2590, in decrypt
    alg, key = pkesk.decrypt_sk(self._key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/pgpy/packet/packets.py", line 225, in decrypt_sk
    m = bytearray(self.ct.decrypt(decrypter, *decargs))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/pgpy/packet/fields.py", line 1773, in decrypt
    return padder.update(_m) + padder.finalize()
                               ^^^^^^^^^^^^^^^^^
ValueError: Invalid padding bytes.
```

**Comment by ajkessel** [comment]
I'll do some more experimenting and see if I can find if there is anything consistent about which messages fail to decrypt.

**Comment by opulentfox-29** [comment]
> But that won't do much, unless you can check that passphrase is a valid hex

You still haven't answered the question whether your passphrase is encoded in hex and contains exactly 64 characters.
just while I was working on `hydroxide` I noticed that it stores the password in base64, maybe your passphrase is the same too.

Reproduce these steps and see the contents of the `passphrase` variable
https://github.com/opulentfox-29/protonmail-api-client/issues/35#issuecomment-2526196145

**Comment by opulentfox-29** [comment]
> Thunderbird-->Hydroxide

I was able to reproduce the error, sent a message via `hydroxide` and when reading in `protonmail-api-client` I got `ValueError: Invalid padding bytes.`

**Comment by ajkessel** [comment]
> Reproduce these steps and see the contents of the `passphrase` variable

Sorry, yes, `passphrase` shows as a 64-byte hexadecimal string.

**Comment by ajkessel** [comment]
> I was able to reproduce the error, sent a message via `hydroxide` and when reading in `protonmail-api-client` I got `ValueError: Invalid padding bytes.`

So it's odd as I thought `hydroxide` just passes the sent message to protonmail over the API to encrypt and send. I didn't think `hydroxide` was handling the encryption but I haven't dug in on that.

**Comment by ajkessel** [comment]
Would it make sense to look at switching to a wrapper like [python-gnupg](https://github.com/vsajip/python-gnupg) or would that be too much overhead/performance hit?

**Comment by opulentfox-29** [comment]
> Would it make sense to look at switching to a wrapper like [python-gnupg](https://github.com/vsajip/python-gnupg)

no, for 2 reasons:
1. it requires the user to have `GPG` installed beforehand (it takes more effort than just `pip isntall`)
2. it is a wrapper over `GPG`, which has very few available methods, and for sending a message to protonmail, and decrypting attachments, the `encryptSessionKey/decryptSessionKeys` functions are required, which are not available from `GPG`, in `PGPy` I studied the algorithm of its work for this and wrote this:
```python
with pgp_private_key.unlock(pair_keys.passphrase) as key:
    subkey = tuple(dict(key.subkeys).values())[0]
    pkesk = encrypted_message._sessionkeys[0]
    alg, aes256_key = pkesk.decrypt_sk(subkey._key)
```
many private attributes (with underscores at the beginning) indicate that this should not be the case, but I have not found any other libraries except `OpenPGP.js` that provide similar functionality

**Comment by opulentfox-29** [comment]
> I thought `hydroxide` just passes the sent message to protonmail over the API to encrypt and send.

Then it would be a violation of protonmail's ideology of mail security. if it were possible to simply transmit an unencrypted message to the protonmail server then a man in the middle (MITM) could simply intercept it, so it is the client that should be encrypting and decrypting the message, and protonmail should simply store an encrypted copy of the message.

**Comment by ajkessel** [comment]
> > I thought `hydroxide` just passes the sent message to protonmail over the API to encrypt and send.
> 
> Then it would be a violation of protonmail's ideology of mail security. if it were possible to simply transmit an unencrypted message to the protonmail server then a man in the middle (MITM) could simply intercept it, so it is the client that should be encrypting and decrypting the message, and protonmail should simply store an encrypted copy of the message.

OK, I'm probably wrong about how `hydroxide` works then -- I haven't dug in deeply. It seems like it is encrypting sent messages in a way that the other Proton clients (web, mobile, official bridge) can decrypt, but not protonmail-api-client. Is the issue [here](https://github.com/emersion/hydroxide/blob/c964219ad4996d90b34d730b98a8c736b9bc9921/protonmail/messages.go#L482)? If it's not possible to fix this on the protonmail-api-client side due to some limitations on pgpy, maybe I should submit a patch to hydroxide since it must be doing something differently from the way the other Proton clients do for sending mail.

**Comment by opulentfox-29** [comment]
I don't know, I'm still trying to figure out what the difference is between messages sent via `hydroxide` and via other clients.
If I can find the problem, I can try to replace the data in `PGPy` to make it work like `OpenPGP.js`

**Comment by ajkessel** [comment]
It is definitely a different passphrase on those messages that are failing versus those that succeed, but the passphrase is the same number of characters and appears to be the same [0-9a-f] encoding.

**Comment by opulentfox-29** [comment]
The problem is both in `hydroxide` and in `PGPy`.
- `hydroxide` for some reason generates a pgp message twice as big as `OpenPGP.js`
- `PGPy` can't work with this type of message.

I couldn't replace the data so that `PGPy` would work. I also don't think that `hydroxide` will fix this error because `OpenPGP.js` (web interface) works, which means their job is done. But of course you can try to write to them.

I think the end result is this: reading a message sent by `hydroxide` using `protonmail-api-client` won't work. Maybe in the future something better than `PGPy` will appear and then it will become possible.
