### ISSUE TITLE
Can't send message (KeyError)

### ISSUE THREAD

**Issue by stefanodvx** [opulentfox-29/protonmail-api-client#4]
HI! I'm trying to send a message... This is my current code (without the login part)
```py3
recipients = ["email@proton.me"]
subject = "My first message"
body = "Ciao!"  # html or just text

new_message = proton.create_message(
    recipients=recipients,
    subject=subject,
    body=body
)

sent_message = proton.send_message(new_message)
```

...and this is the error i get
```
C:\Users\Stefano\Desktop\test>py -3.11 proton.py
login success
C:\Users\Stefano\AppData\Local\Programs\Python\Python311\Lib\site-packages\pgpy\constants.py:192: CryptographyDeprecationWarning: IDEA has been deprecated
  bs = {SymmetricKeyAlgorithm.IDEA: algorithms.IDEA,
C:\Users\Stefano\AppData\Local\Programs\Python\Python311\Lib\site-packages\pgpy\constants.py:194: CryptographyDeprecationWarning: CAST5 has been deprecated
  SymmetricKeyAlgorithm.CAST5: algorithms.CAST5,
C:\Users\Stefano\AppData\Local\Programs\Python\Python311\Lib\site-packages\pgpy\constants.py:195: CryptographyDeprecationWarning: Blowfish has been deprecated
  SymmetricKeyAlgorithm.Blowfish: algorithms.Blowfish,
C:\Users\Stefano\AppData\Local\Programs\Python\Python311\Lib\site-packages\protonmail\pgp.py:71: UserWarning: Selected compression algorithm not in key preferences
  encrypted_message = str(public_key.encrypt(message))
Traceback (most recent call last):
  File "C:\Users\Stefano\Desktop\test\proton.py", line 24, in <module>
    sent_message = proton.send_message(new_message)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python311\Lib\site-packages\protonmail\client.py", line 253, in send_message
    response = self._post(
               ^^^^^^^^^^^
KeyError: 'Sent'
```

**Comment by opulentfox-29** [comment]
Hello, at the moment it is not possible to send a message to address @proton.me/@protonmail.com because this requires additional encryption.
For now, use a different address.

**Comment by stefanodvx** [comment]
@opulentfox-29 tried again sending email to a gmail.com address. now i dont get any error, and i get a Message object back. but no message is sent? I checked both proton and gmail accounts, there's nothing sent.

**Comment by Jaden024** [comment]
Is there a way to send the message without the signature attached?

**Comment by opulentfox-29** [comment]
> Is there a way to send the message without the signature attached?

This will now be the default.
https://github.com/opulentfox-29/protonmail-api-client/issues/6

**Comment by opulentfox-29** [comment]
@stefanodvx maybe there was a problem with the private key, in the new version [1.4.0](https://pypi.org/project/protonmail-api-client/1.4.0/) all keys are received automatically, try sending a message now to gmail.com

### Install
```
pip install protonmail-api-client==1.4.0
```

### Use
```python
from protonmail import ProtonMail

username = "YouAddress@proton.me"
password = "YourPassword123"

proton = ProtonMail()
proton.login(username, password)

recipients = ["to@gmail.com"]
subject = "My first message"
body = "<html><body>hello, i sent my first mail!</body></html>"

new_message = proton.create_message(
    recipients=recipients,
    subject=subject,
    body=body
)

sent_message = proton.send_message(new_message)

```
also do not forget that gmail can identify all letters from protonmail as spam\scam, check your spam folder. and all the messages you sent in protonmail are not in the “inbox” folder, but in the "[sent](https://mail.proton.me/u/0/sent)" folder or in the "[all mail](https://mail.proton.me/u/0/almost-all-mail)" folder
if the message could not be sent, maybe there will be a [draft](https://mail.proton.me/u/0/drafts)

**Comment by stefanodvx** [comment]
works. ty.
