### ISSUE TITLE
Can't find a way to send messages without the signature attached

### ISSUE THREAD

**Issue by Jaden024** [opulentfox-29/protonmail-api-client#6]
How can i do that?

**Comment by Jaden024** [comment]
@opulentfox-29 Дружище, уже весь твой код облазил, не могу понять как отослать без этого инкрипта прикрепленного XD

**Comment by opulentfox-29** [comment]
since version 1.3.2 all sent messages will not have a signature.asc
update version:
```
pip install protonmail-api-client==1.3.2
```

**Comment by Jaden024** [comment]
Thabjs a lot, you're the best! @opulentfox-29
