### ISSUE TITLE
Cannot finish login with proton.login

### ISSUE THREAD

**Issue by antopiahk** [opulentfox-29/protonmail-api-client#8]
I am using the code from the getting started documentation.
```
from protonmail import ProtonMail
import os
from dotenv import load_dotenv

load_dotenv()

PROTON_PASSWORD= os.getenv("PROTON_PASSWORD")

username = "...@domain"
password = PROTON_PASSWORD

proton = ProtonMail()
proton.login(username, password)

...
```

This is the output I get in the console:
```
login success
Traceback (most recent call last):
  File "C:\lorem\mail.py", line 13, in <module>
    proton.login(username, password)
  File ".venv\Lib\site-packages\protonmail\client.py", line 87, in login
    self._parse_info_after_login()
  File "C:\lorem\.venv\Lib\site-packages\protonmail\client.py", line 765, in _parse_info_after_login
    address = self.__addresses()['Addresses'][0]
              ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'Addresses'
```
Note that I get the green message "login success".

Thanks for any help.

EDIT:
I believe I found the issue. If I'm not mistaken, its due to 2FA enabled on my account.
![image](https://github.com/opulentfox-29/protonmail-api-client/assets/31695089/e8575d65-c9ce-45d5-99dd-de42f450eb90)

**Comment by antopiahk** [comment]
I resolved this issue by completely turning off 2FA for my account. This includes also turning off the 2FA requirements for business accounts.

Hope this might help anyone else having this issue!

**Comment by opulentfox-29** [comment]
Now you can use Two-Factor Authentication(2FA).
Just repeat login and you will be asked for a 2FA code.
```python
proton.login(username, password)
```
```shell
enter 2FA code:
>? 123456
```
Or if you have a function that receives a 2FA code, use it:
```python
def some_function_for_get_2fa_code() -> int:
    code = 123456  # some logic
    return code

proton.login(username, password, getter_2fa_code=some_function_for_get_2fa_code)
```

Warning:
only TOTP is supported, U2F/FIDO (like USB key) is unsupported.
